version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      docker: 18 
  build:
    commands:
      - export PYTHONUNBUFFERED=TRUE
      - export SAGEMAKER_PROJECT_NAME_ID="${SAGEMAKER_PROJECT_NAME}-${SAGEMAKER_PROJECT_ID}"
      - echo "Cloning torch-points3d"
      - git clone https://github.com/nicolas-chaulet/torch-points3d
      - echo "Moving hydra configuration"
      - mv scripts/custom.yaml torch-points3d/conf/hydra/job_logging/custom.yaml
      - echo "Moving dockerignore"
      - mv scripts/.dockerignore torch-points3d/.dockerignore
      - echo "Loading sagemaker_training.py"
      - mv scripts/sagemaker_train.py torch-points3d/sagemaker_train.py
      - echo "Building docker training image and uploading to ecr"
      - sh build_and_push.sh docker-train/Dockerfile ${ECR_TRAINING_CONTAINER}
      - echo "Building docker inference image and upload to ecr"
      - sh build_and_push.sh docker-inference/Dockerfile ${ECR_INFERENCE_CONTAINER}
